apiVersion: v1
kind: ConfigMap
metadata:
    name: game-demo-file
    namespace: anisa
data:
    game.properties: |
      enemy.types=aliens,monsters
      player.lives=3
    user-interfaces.properties: |
      color.good=green
      color.bad=yellow
      allow.textmode=true