apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: testi
    namespace: anisa
subjects:
    - kind: User
      name: Bob
      apiGroups: [""]
roleRef:
    - kind: ClusterRole
      name: secrets-reader
      apiGroup: rbac.authorization.k8s.io/v1