apiVersion: v1
kind: PersistentVolume
metadata:
  name: anisa-pv
spec:
  volumeMode: Filesystem # Block ---> like ceph rbd
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain # Recycle --> rm -rf (/thevolume/*)  # Delete ---> باید استوریج انجین پشتش دستور delete رو بفهمه
  hostPath:
    path: "/home/anisa-pv"