apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anisa-pvc
  namespace: anisa
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: anisa-pv