apiVersion: v1
kind: Deployment
metadata: 
  name: mysql-DB
  namespace: anisa
  labels:
    app: mydb
spec:
    selector:
      matchLabels:
        app: mysql
    temmplate:
      metadata:
        labels:
          app: mysql
      spec:
        containers:
          - name: mydb
            image: mysql:latest
            ports:
              - containerPort: 3308
            env:
              - name: MYSQL_ROOT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mysql-secret
                    key: password
              - name: MYSQL_DATABASE
                value: "anisa"
      restartPolicy: Never