apiVersion: v1
kind: Deployment
metadata:
  name: docker-test
  namespace: anisa
  labels:
    app: mysql
spec:
  selector:
    matchLables:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: "mysql"
          image: mysql:1.18
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: "50m"
              memory: "1Gi"
            limits:
              cpu: "100m"
              memory: "2Gi"
      restartPolicy: On-Failure
      imagePullSecrets:
          - name: dockercfgjsn