apiVersion: v1
kind: Secret
metadata:
  name: dockercfgjsn
  namespace: anisa
type: kubernetes.io/dockerconfigjson
data:
  # Example:
  # password: {{ .Values.password | b64enc }}
  .dockerconfigjson: hglsdgp43jhsyhv213 # encrypt this related to your private Registry ==>{"auths":{"REPO_NAME":{"auth":"TOKEN","password":"PASSWORD","username":"USERNAMEW"}}}
