apiVersion: v1
kind: Deployment
metadata:
  name: myDB
  namespace: anisa
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql-DB
  temmplate:
    metadata:
      labels:
        app: mysql-DB
    spec:
      containers:
        - name: mydb
          image: mysql
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: secret
              path: "/secret"
              readOnly: true
      volumes:
        - name: secret
          secret:
            secretName: mysql-secret